#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024-2026 The XTC Project Authors
#
from typing import Any, Hashable, TypeVar
from collections.abc import Callable, Iterator, Generator
import logging

from .math import estimate_unique_prob_good_turing, estimate_richness_chao1

__all__ = [
    "sample_uniques",
    "gen_sample_uniques",
]

logger = logging.getLogger(__name__)

Sample = TypeVar("Sample")


def gen_sample_uniques(
    draw: Callable[[int], Iterator[Sample]],
    num: int,
    prob: float = 1 / 1000,
) -> Generator[Sample, None, None]:
    """
    Algorithm to sample from an unknown design space size
    unique values given some draw function with no prerequisite.

    The draw function may be any function returning an Iterator of Hashable
    function of at most some given number of samples.

    The draw function may not give any guarantee of:
    - uniqueness,
    - non-empty return,
    - exact return count,
    - uniformity of sample distributions.

    This algorithm will return:
    - unique samples,
    - empty samples when the draw function is sparse and stop condition reached.

    The algorithms proceed by rounds of round_num draws, where
    round_num is initialized to num and multiplied by a factor of 2
    if no sample is drawn for a round.

    The rounds stop when either:
    - the requested num of sample is reached, or
    - the probability estimate of a new unique draw is lowerthan the stop probability.

    The stop probability defaults to 1/1000, i.e. predicting 1 new over 1000 draws.

    Args:
        draw: the draw function taking an int and returning an iterator of hashable
        num: the requested number of samples
        prob: stop condition probability of 1 new unique

    Returns:
        generator of unique such samples of at most num elements
    """

    round_num = num
    count = 0
    seen: set[Hashable] = set()
    once: set[Hashable] = set()
    twice: set[Hashable] = set()
    draws = 0
    requests = 0
    p_valid, p_unseen = 1.0, 1.0
    p_next = p_valid * p_unseen
    while count < num and p_next >= prob:
        logger.debug(
            "sample_uniques round: count: %d/%d, p_unseen: %g, p_valid: %g, "
            "p_new: %g > %g, draws: %d, requests: %d, once: %s, twice: %d",
            count,
            num,
            p_unseen,
            p_valid,
            p_next,
            prob,
            draws,
            requests,
            len(once),
            len(twice),
        )
        round_draws = 0
        round_count = 0
        for sample in draw(round_num):
            try:
                _ = set([sample])
            except TypeError as e:
                raise TypeError(
                    f"sample_uniques(): sample type must be hashable: {sample}: {e}"
                )
            round_draws += 1
            if sample not in seen:
                seen.add(sample)
                round_count += 1
                yield sample
                once.add(sample)
            elif sample in once:
                once.remove(sample)
                twice.add(sample)
            elif sample in twice:
                twice.remove(sample)
        requests += round_num
        draws += round_draws
        count += round_count
        p_valid = max(1 / (requests + 1), draws / requests)
        p_unseen = estimate_unique_prob_good_turing(draws, len(once))
        p_next = p_unseen * p_valid
        if round_draws == 0:
            round_num *= 2
    logger.debug(
        "sample_uniques sampled: count: %d/%d, p_unseen: %g, p_valid: %g, p_next: %g, "
        "draws: %d, requests: %d, once: %s, twice: %d",
        count,
        num,
        p_unseen,
        p_valid,
        p_next,
        draws,
        requests,
        len(once),
        len(twice),
    )


def sample_uniques(
    draw: Callable[[int], Iterator[Sample]],
    num: int,
    *args: Any,
    **kwargs: Any,
) -> list[Sample]:
    """
    Returns list of samples generated by gen_samples_uniques()
    Args:
        draw: the draw function taking an int and returning an iterator of hashable
        num: the requested number of samples
        *args, **kwargs: other arguments passed to gen_samples_uniques()

    Returns:
        list of unique samples of at most num elements
    """
    return list(gen_sample_uniques(draw, num, *args, **kwargs))
